
SELECT COUNT(*) 선수인원
FROM PLAYER P 
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC;

-- 1단계
SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P 
WHERE P.BIRTH_DATE IS NOT NULL 
ORDER BY P.BIRTH_DATE DESC;

--2단계

SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM (SELECT P.BIRTH_DATE,PLAYER_NAME 
      FROM PLAYER P
      WHERE P.BIRTH_DATE IS NOT NULL
      ORDER BY P.BIRTH_DATE DESC) P 
WHERE ROWNUM BETWEEN 1 AND 10;




SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM (SELECT ROWNUM AS RNUM,P.*
      FROM (SELECT BIRTH_DATE,PLAYER_NAME 
            FROM PLAYER P
            WHERE P.BIRTH_DATE IS NOT NULL
            ORDER BY P.BIRTH_DATE DESC)P
       WHERE ROWNUM <= 10
            )P 
WHERE P.RNUM >= 6;



SELECT P.RNUM NO,
       P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM (SELECT ROWNUM RNUM,P.*
      FROM (SELECT BIRTH_DATE,PLAYER_NAME 
            FROM PLAYER P
            WHERE P.BIRTH_DATE IS NOT NULL
            ORDER BY P.BIRTH_DATE DESC)P
      WHERE ROWNUM BETWEEN 10 AND 468)P 
WHERE P.RNUM BETWEEN 7 AND 500;

